spring:
  application:
    name: project-server
#
swagger:
  basePackage: com.didichuxing.erp.dcloud.project
management:
  endpoints:
    web:
      exposure:
        include: refresh,health
server:
  port: 7111

eureka:
  password: 123
  client:
    serviceUrl:
      defaultZone: http://eureka:${eureka.password}@172.20.201.111:8701/eureka/,http://eureka:${eureka.password}@172.20.201.111:8702/eureka/
#      defaultZone: http://eureka:123@localhost:8701/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    status-page-url-path: /swagger-ui.html
#    home-page-url: /actuator/health