// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package proto.com.example.grpc;

public interface HelloRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reply = 1;</code>
   */
  java.lang.String getReply();
  /**
   * <code>string reply = 1;</code>
   */
  com.google.protobuf.ByteString
      getReplyBytes();
}
