spring:
  application:
    name: starrocks

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://starrocks-dev:32370/test
    username: test
    password: test
# 数据库连接池配置
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 60000
      hikari.max-lifetime: 1800000
      connection-timeout: 10000

server:
  port: 8001